fig, ax = plt.subplots(2, 2)
dryfrac.plot.line(x='time', ax=ax[0, 0])
ax[0, 0].set_title('Dry Fraction')
Ophi.plot.line(x='time', ax=ax[0, 1])
ax[0, 1].set_title('Overlap Values')
fr.plot.line(x='time', ax=ax[1, 0])
ax[1, 0].set_title('Reworked Fraction')
PwetA.plot.line(x='time', ax=ax[1, 1])
ax[1, 1].set_title('Abandoned Fraction')
plt.tight_layout()
plt.show()
