fig, ax = plt.subplots()
ax.plot(0, R[0], 'o')
ax.plot(1, rgh0, 'o')
ax.set_xticks([0, 1])
ax.set_xticklabels(['theory', 'computed'])
ax.set_xlim(-0.5, 1.5)
ax.set_ylim(0, 3)
ax.set_ylabel('shoreline roughness [-]')
plt.show()