# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
        skip-existing: true
        print-hash: true
        verify-metadata: false
